const dataCard = [
    {
        img: './assets/image/none.png',
        genre: 'Action RPG',
        classGenre: '--actionRpg',
        name: 'Dragon Age 5',
        grade: '0',
        stars: [],
        description: '',
        lostPrice: '',
        price: ' ',
        sale: ''
    },
    {
        img: './assets/image/SaintsRow.png',
        genre: 'Action RPG',
        classGenre: '--actionRpg',
        name: 'Saints Row',
        grade: '0',
        description: 'Platinum Edition',
        lostPrice: '$1,299',
        stars: [],
        price: ' 699',
        sale: '-50%'
    },
    {
        img: './assets/image/paladins.png',
        genre: 'Multiplayer RPG',
        classGenre: '--multiplayerRpg',
        name: 'Paladins',
        grade: '1,820',
        stars: ['yellow', 'yellow', 'yellow', 'yellow'],
        description: 'Get the Captain Price Operator included with purchase',
        lostPrice: '',
        price: 'Free',
        sale: ''
    },
    {
        img: './assets/image/farCry6.png',
        genre: 'Action',
        classGenre: '--action',
        name: 'Far Cry 6',
        grade: '2,888',
        stars: ['yellow', 'yellow', 'yellow', 'yellow'],
        description: 'In-Game Content',
        lostPrice: '$1,299',
        price: ' $649',
        sale: '-50%'
    },
    {
        img: './assets/image/CallOfDutyWarzone.png',
        genre: 'Shooter',
        classGenre: '--shooter',
        name: 'Call of Duty: Warzone',
        grade: '18,982',
        stars: ['yellow', 'yellow', 'yellow'],
        description: 'Get the Captain Price Operator included with purchase',
        lostPrice: '$1,299',
        price: ' $649',
        sale: '-50%'
    },
    {
        img: './assets/image/WoW-Shadowlands.png',
        genre: 'Action',
        classGenre: '--action',
        name: 'World of Warcraft: Shadowlands',
        grade: '299',
        stars: ['yellow', 'yellow', 'yellow', 'half'],
        description: 'Includes access to World of Warcraft, Burning Crusade Classic, and WoW Classic!',
        lostPrice: '',
        price: 'Free',
        sale: ''
    },
    {
        img: './assets/image/fortnite.png',
        genre: 'Shooter',
        classGenre: '--shooter',
        name: 'Fortnite',
        grade: '9,199',
        stars: ['yellow', 'yellow', 'yellow', 'yellow', 'half'],
        description: 'Get the Captain Price Operator included with purchase',
        lostPrice: '$1,299',
        price: ' $649',
        sale: '-50%'
    },
    {
        img: './assets/image/HorizonForbiddeWest.png',
        genre: 'Action RPG',
        classGenre: '--actionRpg',
        name: 'Horizon: Forbidden West',
        grade: '9,199',
        stars: ['yellow', 'yellow', 'yellow', 'yellow', 'half'],
        description: 'Platinum Edition',
        lostPrice: '$1,299',
        price: ' $649',
        sale: ''
    },
    {
        img: './assets/image/nfsHeat.png',
        genre: 'Action',
        classGenre: '--action',
        name: 'Need for Speed: Heat',
        grade: '2,911',
        stars: ['yellow', 'yellow', 'yellow', 'yellow', 'half'],
        description: 'Includes access to World of Warcraft, Burning Crusade Classic, and WoW Classic!',
        lostPrice: '',
        price: ' $649',
        sale: ''
    },
    {
        img: './assets/image/SpiderManMilesMorales.png',
        genre: 'Action',
        classGenre: '--action',
        name: 'Spider-Man: Miles Morales',
        grade: '920',
        stars: ['yellow', 'yellow', 'yellow'],
        description: 'Get the Captain Price Operator included with purchase',
        lostPrice: '$1,299',
        price: ' $649',
        sale: '-50%'
    },
    {
        img: './assets/image/WitcherWildHunt.png',
        genre: 'Card Game',
        classGenre: '--card-game',
        name: 'Witcher 3: Wild Hunt',
        grade: '299,890',
        stars: ['yellow', 'yellow', 'yellow', 'yellow', 'yellow'],
        description: 'Will only be usable in the new Classic Format when it is released',
        lostPrice: '$1,299',
        price: ' $649',
        sale: ''
    },
    {
        img: './assets/image/GuardiansGalaxy.png',
        genre: 'Shooter',
        classGenre: '--shooter',
        name: 'Guardians of the Galaxy',
        grade: '29',
        stars: ['yellow', 'yellow', 'yellow'],
        description: 'In-Game Content',
        lostPrice: '$1,299',
        price: ' $649',
        sale: '-50%'
    },
    {
        img: './assets/image/CrashTeamRacing.png',
        genre: 'Shooter',
        classGenre: '--shooter',
        name: 'Fortnite',
        grade: '9,199',
        stars: ['yellow', 'yellow', 'yellow', 'yellow', 'half'],
        description: 'Get the Captain Price Operator included with purchase',
        lostPrice: '$1,299',
        price: ' $649',
        sale: '-50%'
    },
    {
        img: './assets/image/SpiderMan.png',
        genre: 'Multiplayer RPG',
        classGenre: '--multiplayerRpg',
        name: 'Spider-Man',
        grade: '9,199',
        stars: ['yellow', 'yellow', 'yellow', 'yellow', 'half'],
        description: 'Includes access to World of Warcraft, Burning Crusade Classic, and WoW Classic!',
        lostPrice: '',
        price: ' $649',
        sale: ''
    },
    {
        img: './assets/image/none.png',
        genre: 'Action RPG',
        classGenre: '--actionRpg',
        name: 'Dragon Age 5',
        grade: '0',
        stars: [],
        description: '',
        lostPrice: '',
        price: ' ',
        sale: ''
    },
];

export default dataCard;